plugin: openstack.cloud.openstack

keyed_groups:
  - key: openstack.tags
    prefix: tags

groups:
  vdb: "'vdb' in (openstack.tags|list)"

cache: yes
cache_plugin: ansible.builtin.jsonfile
cache_timeout: 30
cache_connection: dynamic_inventory
cache_prefix: os_
